id: P007046
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5995
  title: རི་ཆོས་ངེས་དོན་རྒྱ་མཚོའི་བསྡུས་དོན་ངེས་དོན་མཛེས་རྒྱན་ཚངས་པའི་སྒྲ་དབྱངས་
  author: ''
  volumes:
    8ee7cc4467254c67844ac8b0768ae13f:
      image_group_id: I1KG6022
      title: ''
      volume_number: 1
      total_pages: 326
ebook_metadata:
  title: རི་ཆོས་ངེས་དོན་རྒྱ་མཚོའི་བསྡུས་དོན་ངེས་དོན་མཛེས་རྒྱན་ཚངས་པའི་སྒྲ་དབྱངས་
  author: ''
  sku: P007046
  cover: cover.jpg
  layers:
  - pagination
