id: opecha:P007046
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5995
  title: རི་ཆོས་ངེས་དོན་རྒྱ་མཚོའི་བསྡུས་དོན་ངེས་དོན་མཛེས་རྒྱན་ཚངས་པའི་སྒྲ་དབྱངས་
  volume:
    c6be1b4f510d415ba8adf994b19cc423:
      image_group_id: I1KG6022
      title: Volume 1 of ri chos nges don rgya mtsho'i bsdus don nges don mdzes rgyan
        tshangs pa'i sgra dbyangs
      volume_number: 1
      total_pages: 326
  author: ''
ebook_metadata:
  title: རི་ཆོས་ངེས་དོན་རྒྱ་མཚོའི་བསྡུས་དོན་ངེས་དོན་མཛེས་རྒྱན་ཚངས་པའི་སྒྲ་དབྱངས་
  author: ''
  sku: P007046
  cover: cover.jpg
  layers:
  - pagination
